# Generated by Django 5.2.7 on 2025-11-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondering',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
