# Generated by Django 5.2.7 on 2025-11-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderings', '0002_alter_pondering_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondering',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
