# Generated by Django 5.2.7 on 2025-11-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderings', '0003_alter_pondering_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pondering',
            old_name='user_id',
            new_name='user',
        ),
    ]
