# Generated by Django 5.2.7 on 2025-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderings', '0004_rename_user_id_pondering_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondering',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
